# Generated by Django 2.1.4 on 2019-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=10)),
                ('manufacture', models.CharField(max_length=10)),
                ('firmware_version', models.IntegerField(default=1)),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Firmwaredata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=10)),
                ('firmware_version', models.IntegerField(default=1)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
