# Generated by Django 2.1.4 on 2019-07-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunwoo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='update_date',
        ),
    ]
