# Generated by Django 2.1.4 on 2019-07-20 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sunwoo', '0002_remove_devicedata_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='firmwaredata',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
