# Generated by Django 2.1.4 on 2019-07-20 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sunwoo', '0003_auto_20190721_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='deviceName',
            field=models.CharField(db_column='deviceName', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firmwaredata',
            name='deviceName',
            field=models.CharField(db_column='deviceName', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='deviceid',
            field=models.CharField(db_column='diviceid', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='firmware_version',
            field=models.IntegerField(db_column='firmware_version', default=1),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='manufacture',
            field=models.CharField(db_column='manufacture', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='update_date',
            field=models.DateTimeField(db_column='update_date', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='firmwaredata',
            name='firmware_version',
            field=models.IntegerField(db_column='firmware_version', default=1),
        ),
        migrations.AlterField(
            model_name='firmwaredata',
            name='manufacture',
            field=models.CharField(db_column='manufacture', max_length=10),
        ),
        migrations.AlterField(
            model_name='firmwaredata',
            name='update_date',
            field=models.DateTimeField(db_column='update_date', default=django.utils.timezone.now),
        ),
    ]
