# Generated by Django 2.1.4 on 2019-07-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunwoo', '0004_auto_20190721_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwaredata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='firmware/%Y/%m/%d/file'),
        ),
    ]
