# Generated by Django 2.2.4 on 2019-09-21 12:43

from django.db import migrations, models
import sunwoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('sunwoo', '0005_firmwaredata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwaredata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=sunwoo.models.firmware_ditrectory_path),
        ),
    ]
