# Generated by Django 2.2.4 on 2019-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunwoo', '0006_auto_20190921_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwaredata',
            name='firmware_number',
            field=models.IntegerField(db_column='firmware_number', default=1),
        ),
    ]
