# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=10)),
                ('firmware_version', models.IntegerField(default=1)),
                ('deviceid', models.CharField(max_length=10)),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Firmwaredata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=10)),
                ('firmware_version', models.IntegerField(default=1)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
